;;;; http-frame.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import chicken scheme srfi-1 srfi-13 extras data-structures ports))
(##sys#register-compiled-module
  'http-frame
  (list)
  '((read-frame . http-frame#read-frame)
    (write-frame . http-frame#write-frame)
    (frame-types . http-frame#frame-types))
  (list)
  (list))

;; END OF FILE
